// Background-job Worker has no inline <script> to embed knowledge text into
// the way app/index.html does — it reads the same content from the compiled
// JSON generated by scripts/sync-knowledge.py instead. One generation step,
// one source of truth for both runtimes.
import compiled from "../../knowledge/compiled/knowledge-compiled.json";

export const EXTRACTION_RULES_MD = compiled.EXTRACTION_RULES_MD;
export const DERIVATION_RULES_MD = compiled.DERIVATION_RULES_MD;
export const SCHEMA_REFERENCE_MD = compiled.SCHEMA_REFERENCE_MD;
export const UNIT_CONVERSIONS_MD = compiled.UNIT_CONVERSIONS_MD;
export const GOLDEN_EXAMPLE_V2_TXT = compiled.GOLDEN_EXAMPLE_V2_TXT;
